[synology-drive-client-bin]
source = "regex"
url = "https://www.synology.com/api/releaseNote/findChangeLog?identify=SynologyDriveClient&lang=en-global"
regex = '"version":"(\d+\.\d+\.\d+-\d+)"'

[synology-chat-client-bin]
source = "regex"
url = "https://www.synology.com/api/releaseNote/findChangeLog?identify=ChatClient&lang=en-global"
regex = '"version":"(\d+\.\d+\.\d+-\d+)"'

[msty-studio]
source = "regex"
url = "https://msty.ai/changelog"
regex = 'Msty Studio ([0-9.]+)'

[msty-claw]
source = "regex"
url = "https://msty.ai/claw/changelog"
regex = 'Msty Claw ([0-9.]+)'

[mono-tracker-git]
source = "git"
git = "https://github.com/xonoxc/mono.git"

[bleachbit-tui-git]
source = "git"
git = "https://github.com/bleachbit/bleachbit.git"
branch = "tui"
